Neateller/Neateller/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy

admin.site.site_header = "Skilly - Multiple Services"

admin.site.site_title = "Skilly - Multiple Services"

admin.site.index_title = "Welcome to Skilly Portal"

urlpatterns = [
    path('', include("NeatellerApp.urls")),
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Neateller/NeatellerApp/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView
from . import views
from . views import  index,about_View ,text_View,refund_View,quote_View,page_Temp_View,sucess_View,mybookings_View,thankyou_View,mypayments_View,locations_View,profile_View,booking_View,services_View,terms_View,privary_View,payment_View,contact_View

urlpatterns  = [
	path('', index.as_view(), name='index' ),
	# path('close',  TemplateView.as_view(template_name='close.html'), name='close' ),
	path('about', about_View.as_view(), name='about' ),
	path('profile', profile_View.as_view(), name='profile' ),
	path('locations', locations_View.as_view(), name='locations' ),
	path('mybookings', mybookings_View.as_view(), name='mybookings' ),
	path('mypayments', mypayments_View.as_view(), name='mypayments' ),
	path('testing123', text_View.as_view(), name='testing123' ),
	path('services', services_View.as_view(), name='services' ),
	path('contact', contact_View.as_view(), name='contact' ),
	path('terms', terms_View.as_view(), name='terms' ),
	path('privacy', privary_View.as_view(), name='privacy' ),
	path('refund', refund_View.as_view(), name='refund' ),
	path('quote/<str:Id>', quote_View.as_view(), name='quote/' ),
	path('payment', payment_View.as_view(), name='payment' ),
	path("chk_email/",views.checkemail,name = 'chk_email'),
	path("get_email/",views.getemailtoken,name = 'get_email'),
	path("post_register/",views.pregister_view,name = 'post_register'),
	path("post_login/",views.pLogin_view,name = 'post_login'),
	path("post_preset/",views.pReset_view,name = 'post_preset'),
	path('reset/<str:uidb64>/<str:token>', views.activate, name='reset'),
	path("post_forgot/",views.pForgot_view,name = 'post_forgot'),
	path("post_contact/",views.pContact_view,name = 'post_contact'),
	path('logout', views.logout_view , name='logout'),
	path('logoutsocial', views.logout_social , name='logoutsocial'),

	path('service/<str:Id>', views.service_View, name='service' ),
	path("servicelist/",views.serviceList_View,name = 'servicelist'),
	path("add_section/",views.addSection_view,name = 'add_section'),
	path("add_aboutservice/",views.addAboutServ_view,name = 'add_aboutservice'),
	path("add_Descservice/",views.addDescrServ_view,name = 'add_Descservice'),
	path("add_adonservservice/",views.addadonservServ_view,name = 'add_adonservservice'),
	path("add_offerservice/",views.addofferServ_view,name = 'add_offerservice'),
	path("add_choiceservice/",views.addchoicServ_view,name = 'add_choiceservice'),
	path("add_randchoice/",views.randChoice_view,name = 'add_randchoice'),
	path("add_hourrate/",views.add_hourrate_view,name = 'add_hourrate'),
	path("add_localservice/",views.addlocalServ_view,name = 'add_localservice'),
	path("add_internalservice/",views.addinternalServ_view,name = 'add_internalservice'),
	path("add_advanceservice/",views.addadvanceServ_view,name = 'add_advanceservice'),
	path("add_dateservice/",views.adddateServ_view,name = 'add_dateservice'),
	path("get_servsection/",views.getservSection,name = 'get_servsection'),
	path("get_aboutsection/",views.getaboutSection,name = 'get_aboutsection'),
	path("get_descsection/",views.getdescSection,name = 'get_descsection'),
	path("get_offersection/",views.getofferSection,name = 'get_offersection'),
	path("get_choicesection/",views.getchoiceSection,name = 'get_choicesection'),
	path("get_randomsection/",views.getRandomSection,name = 'get_randomsection'),
	path("get_hoursection/",views.get_hoursectionSection,name = 'get_hoursection'),
	path("get_addonsection/",views.getaddonSection,name = 'get_addonsection'),
	path("get_localaddrsection/",views.getLocaladdrSection,name = 'get_localaddrsection'),
	path("get_interaddrsection/",views.getInteraddrSection,name = 'get_interaddrsection'),
	path("get_servicesection/",views.getServiceSection,name = 'get_servicesection'),
	path("get_Datesection/",views.getDateSection,name = 'get_Datesection'),
	path("get_AppartList/",views.getApprtView,name = 'get_AppartList'),
	path("get_AppartcatList/",views.getApprtCatView,name = 'get_AppartcatList'),
	path("invoice_savePdf/",views.invoice_savePdf_View,name = 'invoice_savePdf'),
	path("invoice_sendPdf/",views.invoice_sendPdfView,name = 'invoice_sendPdf'),
	path("get_LocalAddressList/",views.getLocalAddressView,name = 'get_LocalAddressList'),
	path("get_InternAddressList/",views.getInternAddressView,name = 'get_InternAddressList'),
	path('service/<str:Id>/book-online/job-details', booking_View.as_view(), name='book-online' ),

	path("image_upload/",views.Imgupload_view,name = 'image_upload'),

	path("get_profile/",views.getuserDetails,name = 'get_profile'),
	path("update_profile/",views.profile_update_view,name = 'update_profile'),
	path("get_locations/",views.getlocationDetails,name = 'get_locations'),
	path("get_payments/",views.getpaymentDetails,name = 'get_payments'),
	path("get_bookings/",views.getbookingsDetails,name = 'get_bookings'),
	path("get_countrylist/",views.getcountries,name = 'get_countrylist'),
	path("add_address/",views.addaddresslist,name = 'add_address'),
	path("del_address/",views.deladdresslist,name = 'del_address'),
	path("update_address/",views.updateaddresslist,name = 'update_address'),
	path("create_paymentLink/",views.create_paylink,name = 'create_paymentLink'),
	path('payment/sucess/<str:Id>/', sucess_View.as_view(), name='sucess' ),
	path("webhooks/acme/fsferstrtr55677",views.webhook_endpoint,),
	path("check_payment/",views.checkpayment,name = 'check_payment'),
	path("booking_confirm/",views.booking_confirmview,name = 'booking_confirm'),
	path("cancel_booking/",views.cancel_bookingview,name = 'cancel_booking'),
	path('service/<str:Id>/book-online/confirmation/<str:Id1>/', thankyou_View.as_view(), name='book-online' ),
	]

Neateller/NeatellerApp/models.py
from asyncio import format_helpers
from math import fabs
from operator import truediv
import os
from tkinter import CASCADE
import uuid
from django.db import models
from django.dispatch import receiver
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import redirect,render
import datetime
from django.core.validators import MaxValueValidator
import shortuuid
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _

class UserManager(BaseUserManager):
    def _create_user(self, email, username=None, is_admin=False, is_staff=False, is_active=True, password=None):
        'Method for actual creation of a user'

        if not email:
            raise ValueError('User must have an email')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            is_admin=is_admin,
            is_staff=is_staff,
            is_active=is_active
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username=None, password=None):
        'Create a simple user'
        return self._create_user(email=email, username=username, password=password)

    def create_staffuser(self, email, username=None, password=None):
        'Create a staff user'
        return self._create_user(email=email, username=username, is_staff=True, password=password)

    def create_superuser(self, email, username=None, password=None):
        'Create a super user'
        return self._create_user(
            email=email, username=username, is_admin=True,
             is_staff=True, is_active=True, password=password
        )

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=150, unique=False,default="")
    phoneNumber = models.CharField(max_length=150, unique=False,default="")
    country = models.CharField(max_length=150, unique=False,default="")
    first_name = models.CharField(max_length=250,blank=True,default="")
    last_name = models.CharField(max_length=250,blank=True,default="")
    name = models.CharField(max_length=150, blank=True,default="")
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True)
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return f'{self.email}'

    def get_full_name(self):
        return f'{self.name}'

    def get_short_name(self):
        return f'{self.username}'

    def has_perm(self, perm, obj=None):
        'Does the user have a specific permission?'
        return True

    def has_module_perms(self, app_label):
        'Does the user have permissions to view the app `app_label`?'
        return True

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this User."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def has_staff_perm(self):
        'Is the user a member of staff?'
        return self.is_staff

    @property
    def has_active_perm(self):
        'Is the user active?'
        return self.is_active

    @property
    def has_admin_perm(self):
        'Is the user is super admin?'
        return self.is_admin

class Contactus(models.Model):
    BOOL_CHOICES =[('Received', 'Received'),('Contacted', 'Contacted'),]
    id = ShortUUIDField(length=6,max_length=6,alphabet="123456",primary_key=True,)
    first_name = models.CharField(max_length=250, blank=True, null=True)
    last_name = models.CharField(max_length=250, blank=True, null=True)
    email = models.EmailField(max_length=250, blank=True, null=True)
    phone = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=250, blank=True, null=True)
    countrycode = models.CharField(max_length=250, blank=True, null=True)
    message = models.CharField(max_length=1000, blank=True, null=True)
    status =  models.CharField(max_length=200,choices=BOOL_CHOICES,default='NA',)
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    
    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")

    def __str__(self):
        return str(self.id)

class PopupBuilders(models.Model):

    name = models.CharField(max_length=191)
    type = models.CharField(max_length=191, blank=True, null=True)
    title = models.CharField(max_length=191, blank=True, null=True)
    only_image = models.CharField(max_length=191, blank=True, null=True)
    background_image = models.CharField(max_length=191, blank=True, null=True)
    offer_time_end = models.CharField(max_length=191, blank=True, null=True)
    button_text = models.CharField(max_length=191, blank=True, null=True)
    button_link = models.CharField(max_length=191, blank=True, null=True)
    btn_status = models.CharField(max_length=191, blank=True, null=True)
    lang = models.CharField(max_length=191, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)

    def __str__(self):
        return self.name

class ProductCoupons(models.Model):
    code = models.CharField(max_length=191)
    discount = models.CharField(max_length=191, blank=True, null=True)
    discount_type = models.CharField(max_length=191, blank=True, null=True)
    expire_date = models.CharField(max_length=191, blank=True, null=True)
    status = models.CharField(max_length=191)
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)

    def __str__(self):
        return self.discount

class ProductOrders(models.Model):

    status = models.CharField(max_length=191, blank=True, null=True)
    payment_status = models.CharField(max_length=191, blank=True, null=True)
    transaction_id = models.CharField(max_length=191, blank=True, null=True)
    payment_track = models.CharField(max_length=191, blank=True, null=True)
    payment_gateway = models.CharField(max_length=191, blank=True, null=True)
    user_id = models.CharField(max_length=191, blank=True, null=True)
    subtotal = models.CharField(max_length=191, blank=True, null=True)
    coupon_discount = models.CharField(max_length=191, blank=True, null=True)
    shipping_cost = models.CharField(max_length=191, blank=True, null=True)
    product_shippings_id = models.CharField(max_length=191, blank=True, null=True)
    total = models.CharField(max_length=191, blank=True, null=True)
    billing_name = models.TextField(blank=True, null=True)
    billing_email = models.TextField(blank=True, null=True)
    billing_phone = models.TextField(blank=True, null=True)
    billing_country = models.TextField(blank=True, null=True)
    billing_street_address = models.TextField(blank=True, null=True)
    billing_town = models.TextField(blank=True, null=True)
    billing_district = models.TextField(blank=True, null=True)
    different_shipping_address = models.TextField(blank=True, null=True)
    shipping_name = models.TextField(blank=True, null=True)
    shipping_email = models.TextField(blank=True, null=True)
    shipping_phone = models.TextField(blank=True, null=True)
    shipping_country = models.TextField(blank=True, null=True)
    shipping_street_address = models.TextField(blank=True, null=True)
    shipping_town = models.TextField(blank=True, null=True)
    shipping_district = models.TextField(blank=True, null=True)
    coupon_code = models.CharField(max_length=191, blank=True, null=True)
    cart_items = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)

    def __str__(self):
        return self.status


class ProductRatings(models.Model):

    ratings = models.IntegerField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    product_id = models.PositiveIntegerField()
    user_id = models.PositiveIntegerField()
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)

    def __str__(self):
        return self.message

class ServiceCategories(models.Model):
    name = models.CharField(max_length=500,default=None,null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now(), blank=True , null=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = _("Service Category")
        verbose_name_plural = _("Service Categories")

def servicefilename(instance, filename):
    ext = filename.split('.')[-1]
    filenm = os.path.splitext(filename)[0]
    filename = "%s_%s.%s" % (filenm,instance.name, ext)
    return os.path.join( 'services/'+filename)

class Service(models.Model):
    name = models.CharField(max_length=500)
    category = models.ForeignKey(ServiceCategories,max_length=100,null=True, on_delete=models.CASCADE)

Neateller/NeatellerApp/templates/footer.html
{% load static %}
{% block content %}
<!-- footer area start -->

<style>
    .widget.footer-widget p, .footer-widget.widget_tag_cloud .tagcloud a, .widget.footer-widget.widget_calendar caption, .widget.footer-widget.widget_calendar th, .widget.footer-widget.widget_calendar td
    {
        text-align: justify;
    }
    .cardDetails
    {
        font-weight: 600;
    }
    .cardimage img{
        width: 40%;
    }
</style>
<div class="footer-area bg-blue-02">
    <div class="container padding-top-30">
        <div class="row" id="footer1">
            {% for s in services %}
            
            <div class="col-lg-3">
                <h5>{{s.name}}</h5>
                {% if s.service_set %}
                <ul class="list-unstyled">
                    {% for subsub_cat in s.service_set.all %}
                    {% if subsub_cat.isActive %}
                            <li class="mt-1"><a class="text-white" title="{{ subsub_cat.name }}" href="/service/{{subsub_cat.page}}">{{ subsub_cat.name }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            {% endfor %}
            <div class="col-lg-3">
                <h5>Men Power Supply</h5>
                <ul class="list-unstyled">
                    <li class="mt-1"><a class="text-white" title="Electricians Supply" href="/quote/electricians">Electricians Supply</a></li>
                    <li class="mt-1"><a class="text-white" title="Plumbers Supply" href="/quote/plumbers">Plumbers Supply</a></li>
                    <li class="mt-1"><a class="text-white" title="Masons Supply" href="/quote/masons">Masons Supply</a></li>
                </ul>
            </div>
        </div>   
    </div>
</div>
<footer class="footer-area bg-blue-02 bg-image padding-top-150" style="background-image: url('static/assets/uploads/media-uploader/footer-bg-min1619971609.png');">
    <div class="footer-top padding-bottom-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6"><div class=" footer-widget widget"><div class="footer-widget widget"><div class="about_us_widget style-01"><img src="{% static 'assets/uploads/media-uploader/site-white-logo1618651031.png' %}" class="footer-logo" alt="site_white_logo"><p>We have partnered with the top home cleaning companies in Dubai, who are ready to serve you 7 days a week.</p></div></div></div></div>
            <!-- <div class="col-lg-3 col-md-6"><div class=" footer-widget widget additionalfooter"><h4 class="widget-title style-01">Additional Information</h4><ul class="recent_post_item"><li class="single-recent-post-item">
                <div class="thumb"><img src="{% static 'assets/uploads/media-uploader/thumb-pexels-karolina-grabowska-4239146-min1620223752.jpg' %}" alt=""></div>
                <div class="content">
                    <h4 class="title"><a href="#">A healthy life is a clean life for everyone</a></h4>
                    <span class="time"> <i class="far fa-calendar-alt "></i>23 Apr 2021</span>
                </div>
            </li><li class="single-recent-post-item">
                <div class="thumb"><img src="{% static 'assets/uploads/media-uploader/thumb-pexels-karolina-grabowska-4239032-min1620225734.jpg' %}" alt=""></div>
                <div class="content">
                    <h4 class="title"><a href="#">Cleaning are best business for future</a></h4>
                    <span class="time"> <i class="far fa-calendar-alt "></i>23 Apr 2021</span>
                </div>
            </li></ul></div></div> -->
            
            <div class="col-lg-3 col-md-6"><div class=" footer-widget widget"><div class="footer-widget widget widget_nav_menu"><h4 class="widget-title">Useful Links</h4>
                <ul>	
                <li>
                    <a href="{% url 'index' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'about' %}">About us</a>
                        </li>

<li>
<a href="{% url 'services' %}">Services</a>
</li>
<li>
    <a href="{% url 'contact' %}">Contact us</a>
</li>


</ul></div></div></div>


<div class="col-lg-3 col-md-6"><div class=" footer-widget widget"><div class="footer-widget widget widget_nav_menu"><h4 class="widget-title">Legal Information</h4>
                <ul>	
<li>
    <a href="{% url 'terms' %}">Terms and conditions</a>
</li>
<li>
    <a href="{% url 'privacy' %}">Privacy policy</a>
</li>
<li>
    <a href="{% url 'refund' %}">Payment and refund policy</a>
</li>
</ul></div></div></div>


<div class="col-lg-3 col-md-6"><div class=" footer-widget widget"><h4 class="widget-title">Contact us</h4><ul class="contact_info_list"> <li class="single-info-item">
                <div class="icon">
                    <i class="fa fa-home"></i>
                </div>
                <div class="details">
                    Uae, dubai,deira muteena ,
                    <br>
                    lulu building 1102
                </div>
            </li><li class="single-info-item">
                <div class="icon">
                    <i class="fa fa-phone"></i>
                </div>
                <div class="details">
                    +971 55 548 7771
                </div>
            </li>
            <li class="single-info-item">
                <div class="icon">
                    <i class="fas fa-envelope-open"></i>
                </div>
                <div class="details">
                    support@skillyservices.com
                </div>
            </li>
            <li class="single-info-item">
                <div class="details cardDetails">
                    Sdz Technical Services LLC, accept payments online using Visa and MasterCard credit/debit card in AED.
                </div>
            </li>
            <li class="single-info-item">
                <div class="details cardimage">
                    <img src="{% static 'assets/frontend/images/newvisa.png' %}" alt="visa_card">
                    <img src="{% static 'assets/frontend/images/newmastercard.png' %}"  alt="master_card">
                </div>
            </li>    
        </ul></div></div>
        </div>
    </div>
</div>
<div class="copyright-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="copyright-area-inner">
                © Copyright 2021 . All Right Reserved By SkillY
                </div>
            </div>
        </div>    
    </div>
</div>
</footer>
<!-- footer area end -->
<!-- back to top area start -->
<div class="back-to-top" style="display: none;">
    <span class="back-top"><i class="fa fa-angle-up"></i></span>
</div>
<!-- back to top area end -->


<!-- jquery -->
<script src="{% static 'assets/common/js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'assets/common/js/jquery-migrate-3.3.2.min.js' %}"></script>
<!-- popup -->
<script src="{% static 'assets/common/js/countdown.jquery.js' %}"></script>
<div class="nx-popup-backdrop"></div>
<div class="nx-popup-wrapper only-image-modal">
<div class="nx-modal-content-wrapper">
                <div class="nx-modal-inner-content-wrapper" style="background-image: url('static/assets/uploads/media-uploader/2-min1620215665.png');">
            <div class="nx-popup-close">×</div>
            <div class="nx-modal-content"></div>
        </div>
        </div>
</div>

<style>
    /* for desktop */
.whatsapp_float {
	position:fixed;
    width: 80px;
    height: 80px;
	bottom:40px;
	left:40px;
	background-color:#25d366;
	color:#FFF;
	border-radius:50px;
	text-align:center;
    font-size:30px;
    z-index: 1000000000;
}
.whatsapp_float:hover{
    color: white;
}
.whatsapp-icon {
    margin-top: 15px;
    font-size: 50px;
}
/* for mobile */
@media screen and (max-width: 767px){
     .whatsapp-icon {
        margin-top: 12px;
        font-size: 40px;
     }
    .whatsapp_float {
        width: 65px;
        height: 65px;
        bottom: 20px;
        left: 10px;
        font-size: 22px;
    }
}
</style>
<!-- bootstrap -->
<script src="{% static 'assets/frontend/js/bootstrap.min.js' %}"></script>
<!-- magnific popup -->
<script src="{% static 'assets/frontend/js/jquery.magnific-popup.js' %}"></script>
<!-- wow -->
<script src="{% static 'assets/frontend/js/wow.min.js' %}"></script>
<!-- owl carousel -->
<script src="{% static 'assets/frontend/js/owl.carousel.js' %}"></script>
<script src="{% static 'assets/frontend/js/owl.carousel.min.js' %}"></script>
<!-- waypoint -->
<script src="{% static 'assets/frontend/js/waypoints.min.js' %}"></script>
<!-- counterup -->
<script src="{% static 'assets/frontend/js/jquery.counterup.min.js' %}"></script>
<!-- main js -->
<script src="{% static 'assets/frontend/js/main.js' %}"></script>
<!-- Progress-Bar -->
<script src="{% static 'assets/frontend/js/jQuery.rProgressbar.min.js' %}"></script>
<!-- Progress-Bar -->
<script src="{% static 'assets/frontend/js/active.rProgressbar.js' %}"></script>
<!-- dynamic js -->
<script src="{% static 'assets/frontend/js/dynamic-script.js' %}"></script>
<!-- toastr js -->
<script src="{% static 'assets/common/js/toastr.min.js' %}"></script>
<script src="{% static 'assets/frontend/js/select2.min.js' %}"></script>
<script src="{% static 'assets/frontend/datatable/jquery.dataTables.min.js' %}"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<a href="https://wa.me/+971555487771" class="whatsapp_float" target="_blank"> <i class="fab fa-whatsapp whatsapp-icon"></i></a>
<script>
$( document ).ready(function() {
    //$('#autoservice').autocomplete(words.sort(), render($('.matches')));
});
</script> 
</body></html>
{% endblock %}

Neateller/NeatellerApp/templates/sucess.html
{% load static %}
{% block content %}
<title>SkillY - Sucess Page</title>
<link rel="icon" href="{% static 'assets/images/icon.png' %}" type="image/png">
<link rel="icon" href="{% static 'assets/images/icon.png' %}" sizes="20x20" type="image/png">
<link rel="stylesheet" href="{% static 'assets/frontend/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/frontend/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/frontend/css/style.css' %}">
<link rel="stylesheet" href="{% static 'assets/frontend/css/responsive.css' %}">
<link rel="stylesheet" href="{% static 'assets/frontend/css/custom-style.css' %}">
<style type="text/css">

    body
    {
        background:#f2f2f2;
    }

    .payment
	{
		border:1px solid #f2f2f2;
		height:280px;
        border-radius:20px;
        background:#fff;
	}
   .payment_header
   {
	   background:#e424b7;
	   padding:20px;
       border-radius:20px 20px 0px 0px;
	   
   }
   
   .check
   {
	   margin:0px auto;
	   width:50px;
	   height:50px;
	   border-radius:100%;
	   background:#fff;
	   text-align:center;
   }
   
   .check i
   {
	   vertical-align:middle;
	   line-height:50px;
	   font-size:30px;
   }

    .content 
    {
        text-align:center;
    }

    .content  h1
    {
        font-size:25px;
        padding-top:25px;
    }
    .content p
    {
        padding: 5%;
    }
    .content a
    {
        width:200px;
        height:35px;
        color:#fff;
        border-radius:30px;
        padding:5px 10px;
        background:#e424b7;
        transition:all ease-in-out 0.3s;
    }

    .content a:hover
    {
        text-decoration:none;
        background:#000;
    }

</style>
<div class="topbar-area">
<div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="topbar-inner">
                        <div class="col-lg-3 left-contnet">
                            <a href="/" class="logo">
                                <img src="http://127.0.0.1:8000/static/assets/uploads/media-uploader/site-white-logo1618651031.png" alt="site_logo" href="/" width="100%">
                            </a>                                                                                                                                            
                        </div>
                        <div class="col-lg-9 right-contnet">
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="container">
    <div class="row">
       <div class="col-md-6 mx-auto mt-5">
          <div class="payment">
             <div class="payment_header">
                <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
             </div>
             <div class="content">
                <h1>Payment Success !</h1>
                <p>Payment for your service have been Sucessfully received please go back to the booking page and complete your order. </p>
             </div>
             
          </div>
       </div>
    </div>
 </div>
 {% endblock %}